### ISSUE TITLE
Colormaps used in Figures 4 and 5

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammaskynet-gamma2016#13]
I find the colormaps used in Figures 4 and 5 a bit odd.

E.g. a Haslam radio image is shown in both Figure 4 and Figure 5, but I think the color map is different? I think it should be the same for the same data, just different regions on the sky.

Also the Planck R1 HFI image in Figure 5 is very colorful.
Wouldn't it be better to use the same colormap as Planck R2 LFI,
so that it's easier to see / compare the two different Planck maps.
Currently I don't know if those are almost the same or which I should look at for comparison with my gamma-ray data. (we'll figure that out and describe it with a sentence or two).

So generally: I like the colormap in the top right figure in Figure 5. I think we could just use that for all the MWL images, or at least use a few less / less colorful maps.

If you have time to re-do the Figure, an idea could also be to show a higher-resolution image of the Galactic plane, by going full-width, and not so high, and putting the panels on top of each other.

**Comment by vorugantia** [comment]
- Fixed Figure 4 of the Galactic plane. All images are in their native color map (which happen to be more colorful than not...) except for the radio image.
- I accidentally fixed my picture of the Cygnus region rather than the Vela region. Is it okay that I switched out Figure 5 for the Cygnus region?

I pushed these new images in a commit. Closing the issue...
